#!/bin/bash

# Install nginx
apt-get update
apt-get -y install nginx

# Configure nginx to listen on port 80 and serve "Hello World!" on root request
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
                echo 'Hello World!';
        }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
