#!/usr/bin/env bash
#Install nginx on your web-01
# Configure nginx to listen on port 80 and serve "Hello World!" on root request
# Restart nginx

apt-get update
apt-get -y install nginx
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
                echo 'Hello World!';
        }
}" > /etc/nginx/sites-available/default
service nginx restart
