#!/usr/bin/env bash
# Installs Nginx with specific configurations
sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

sudo service nginx restart
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null
echo "Nginx installed and configured to listen on port 80. Root URL returns 'Hello World!'"
