#!/usr/bin/env bash
#to configure a new server

sudo apt-get update
sudo apt-get -y install nginx
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/nginx.conf > /dev/null
sudo systemctl restart nginx
