#!/usr/bin/env bash
#to configure a new server

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo grep -qxF 'add_header X-Served-By $hostname;' /etc/nginx/nginx.conf || sudo sed -i '/http {/a \        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
