#!/usr/bin/env bash
apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yeis/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
