#!/usr/bin/bash
sudo apt-get update
sudo apt-get install -y ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 8080/tcp
sudo ufw enable

sudo sed -i 's/^\(DEFAULT_FORWARD_POLICY\).*/\1="ACCEPT"/' /etc/default/ufw
sudo sed -i 's/^#net\/ipv4\/ip_forward=.*/net\/ipv4\/ip_forward=1/' /etc/ufw/sysctl.conf
sudo ufw reload
sudo ufw route allow proto tcp from any to any port 8080
